### ISSUE TITLE
Docker file does not support M1 Mac?

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/fixmystreet#3629]
When trying to install FixMyStreet using Docker I get this error message. I'm on a M1 Mac, maybe is related?

```
fixmystreet-postgres-1     | runtime: failed to create new OS thread (have 2 already; errno=22)
fixmystreet-postgres-1     | fatal error: newosproc
fixmystreet-postgres-1     | 
fixmystreet-postgres-1     | runtime stack:
fixmystreet-postgres-1     | runtime.throw(0x4cb21f, 0x9)
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/panic.go:566 +0x95
fixmystreet-postgres-1     | runtime.newosproc(0xc420028000, 0xc420037fc0)
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/os_linux.go:160 +0x194
fixmystreet-postgres-1     | runtime.newm(0x4d6db8, 0x0)
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/proc.go:1572 +0x132
fixmystreet-postgres-1     | runtime.main.func1()
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/proc.go:126 +0x36
fixmystreet-postgres-1     | runtime.systemstack(0x53ae00)
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
fixmystreet-postgres-1     | runtime.mstart()
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/proc.go:1079
fixmystreet-postgres-1     | 
fixmystreet-postgres-1     | goroutine 1 [running]:
fixmystreet-postgres-1     | runtime.systemstack_switch()
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760
fixmystreet-postgres-1     | runtime.main()
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768
fixmystreet-postgres-1     | runtime.goexit()
fixmystreet-postgres-1     | 	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0
fixmystreet-postgres-1 exited with code 2
fixmystreet-fixmystreet-1  | Still waiting for postgres.svc... 
```

**Comment by dracos** [comment]
This should be resolved by the docker dev environment added since.
